# Generated by Django 4.0.6 on 2022-08-07 18:13

import account.models
import datetime
from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, default='name', null=True)),
                ('mail', models.TextField(blank=True, default='', null=True)),
                ('birthday', models.DateField(blank=True, default='', null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=account.models.upload_location)),
                ('color', models.CharField(default='blue', max_length=250)),
                ('coins', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list, size=None)),
                ('sum_of_coins', models.IntegerField(default=0)),
                ('confirmed', models.BooleanField(default=True)),
                ('confirmation_code', models.CharField(default='', max_length=250)),
                ('confirmation_time', models.DateTimeField(default=datetime.datetime(2000, 1, 1, 0, 0))),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['sum_of_coins', '-birthday', 'id'],
            },
        ),
    ]
