# Generated by Django 4.0.6 on 2022-08-13 08:57

from django.db import migrations, models
import django.db.models.deletion
import task.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('content', '0001_initial'),
        ('account', '0002_profile_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.TextField(blank=True, default='name', null=True)),
                ('problem', models.TextField(blank=True, default='name', null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=task.models.upload_location)),
                ('answer', models.TextField(blank=True, default='name', null=True)),
                ('source', models.TextField(blank=True, default='name', null=True)),
            ],
            options={
                'ordering': ['level', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TaskPaperOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0)),
                ('type_of', models.CharField(default='main', max_length=10)),
                ('content', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='content.paper')),
                ('task', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='task.task')),
            ],
        ),
        migrations.AddField(
            model_name='task',
            name='hints',
            field=models.ManyToManyField(through='task.TaskPaperOrder', to='content.paper'),
        ),
        migrations.AddField(
            model_name='task',
            name='who_solved',
            field=models.ManyToManyField(related_name='solved_problems', to='account.profile'),
        ),
    ]
