# Generated by Django 4.0.6 on 2022-08-13 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
