# Generated by Django 4.0.6 on 2022-08-13 08:57

import content.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, default='Untitled lemma', null=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0)),
                ('image', models.ImageField(blank=True, null=True, upload_to=content.models.upload_location)),
                ('type_of', models.CharField(default='text', max_length=10)),
                ('text', models.TextField(blank=True, default='name', null=True)),
                ('lemma', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='content.paper')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
